// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.1
//   protoc               v5.26.1
// source: proto/auth.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "auth";

export interface Empty {
}

export interface Pagination {
  page: number;
  skip: number;
}

export interface CreateUserRequest {
  email: string;
  password: string;
  age: number;
  subscribed: boolean;
  socialMedia: SocialMedia | undefined;
}

export interface FindAllUsersResponse {
  users: User[];
}

export interface FindUserByIdRequest {
  id: string;
}

export interface User {
  id: string;
  email: string;
  password: string;
  age: number;
  subscribed: boolean;
  socialMedia: SocialMedia | undefined;
}

export interface SocialMedia {
  twitterUri?: string | undefined;
  facebookUri?: string | undefined;
}

export const AUTH_PACKAGE_NAME = "auth";

export interface UserServiceClient {
  createUser(request: CreateUserRequest): Observable<User>;

  findAllUsers(request: Empty): Observable<FindAllUsersResponse>;

  findUserById(request: FindUserByIdRequest): Observable<User>;

  updateUser(request: User): Observable<User>;

  deleteUser(request: FindUserByIdRequest): Observable<Empty>;

  queryUser(request: Observable<Pagination>): Observable<FindAllUsersResponse>;
}

export interface UserServiceController {
  createUser(request: CreateUserRequest): Promise<User> | Observable<User> | User;

  findAllUsers(request: Empty): Promise<FindAllUsersResponse> | Observable<FindAllUsersResponse> | FindAllUsersResponse;

  findUserById(request: FindUserByIdRequest): Promise<User> | Observable<User> | User;

  updateUser(request: User): Promise<User> | Observable<User> | User;

  deleteUser(request: FindUserByIdRequest): Promise<Empty> | Observable<Empty> | Empty;

  queryUser(request: Observable<Pagination>): Observable<FindAllUsersResponse>;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createUser", "findAllUsers", "findUserById", "updateUser", "deleteUser"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = ["queryUser"];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
